vich_uploader:
    db_driver: orm

    mappings:
        articles_front:
            uri_prefix: /images/articles_front
            upload_destination: '%kernel.project_dir%/public/images/articles_front'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        product_image_card:
            uri_prefix: /images/product_image_card
            upload_destination: '%kernel.project_dir%/public/images/product_image_card'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true avatar_image
        avatar_image:
            uri_prefix: /images/avatar_image
            upload_destination: '%kernel.project_dir%/public/images/avatar_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true avatar_image